apiVersion: 1

services:
  - type: web
    name: demotextiles-api
    env: python
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --worker-class gthread --threads 8 --workers 1 -b 0.0.0.0:$PORT app:app"
    healthCheckPath: /api/v1/health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGINS
        # include your static site URL after first deploy, comma-separated if multiple
        value: "https://demotextiles.onrender.com,http://localhost:5173"

staticSites:
  - name: demotextiles-web
    rootDir: frontend
    buildCommand: "npm ci && npm run build"
    publishPath: dist
    # free tier friendly; no plan/instances for static
    envVars:
      - key: VITE_API_URL
        value: "https://demotextiles-api.onrender.com/api/v1"
      - key: NODE_VERSION
        value: "20"
    routes:
      # SPA routing so deep links work
      - type: rewrite
        source: "/*"
        destination: "/index.html"
