# render.yaml — Flask API + Vite SPA

services:
  # --- API (Flask) ---
  - type: web
    name: gt-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -k gthread --threads 4 -t 120 -b 0.0.0.0:$PORT app:app
    healthCheckPath: /api/v1/health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false

  # --- Frontend (Vite SPA served statically) ---
  - type: web
    name: gt-web
    env: static                # static runtime (CDN)
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: VITE_API_URL
        value: "https://gt-api.onrender.com/api/v1"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
