apiVersion: 1

services:
  - type: web
    name: gt-api
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 2 -k gthread -t 120 -b 0.0.0.0:${PORT} app:app"
    healthCheckPath: /api/v1/health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
    # optional but helps deterministic builds:
    pythonVersion: 3.10.13

staticSites:
  - name: gt-web
    rootDir: frontend
    buildCommand: "npm ci && npm run build"
    publishPath: dist
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: VITE_API_URL
        value: "https://gt-api.onrender.com/api/v1"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
